/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface EnjinGallery {}
  interface EnjinGalleryAttributes extends StencilHTMLAttributes {}

  interface EnjinOrganism {
    'component': {
      docs: string;
      docsTags: any[];
      encapsulation: string;
      events: any[];
      methods: any[];
      props: {
        attr: string;
        default: any;
        docs: string;
        docsTags: any[];
        mutable: boolean;
        name: string;
        optional: boolean;
        reflectToAttr: boolean;
        required: boolean;
        type: string;
      }[];
      readme: string;
      slots: any[];
      styles: any[];
      tag: string;
      usage: any;
    };
  }
  interface EnjinOrganismAttributes extends StencilHTMLAttributes {
    'component'?: {
      docs: string;
      docsTags: any[];
      encapsulation: string;
      events: any[];
      methods: any[];
      props: {
        attr: string;
        default: any;
        docs: string;
        docsTags: any[];
        mutable: boolean;
        name: string;
        optional: boolean;
        reflectToAttr: boolean;
        required: boolean;
        type: string;
      }[];
      readme: string;
      slots: any[];
      styles: any[];
      tag: string;
      usage: any;
    };
  }

  interface EnjinPayWithCard {
    'stripeKey': string;
  }
  interface EnjinPayWithCardAttributes extends StencilHTMLAttributes {
    'onEnjinCardSubmit'?: (event: CustomEvent) => void;
    'stripeKey'?: string;
  }

  interface EnjinSidebarComponent {
    'component': {
      docs: string;
      docsTags: any[];
      encapsulation: string;
      events: any[];
      methods: any[];
      props: {
        attr: string;
        default: any;
        docs: string;
        docsTags: any[];
        mutable: boolean;
        name: string;
        optional: boolean;
        reflectToAttr: boolean;
        required: boolean;
        type: string;
      }[];
      readme: string;
      slots: any[];
      styles: any[];
      tag: string;
      usage: any;
    };
  }
  interface EnjinSidebarComponentAttributes extends StencilHTMLAttributes {
    'component'?: {
      docs: string;
      docsTags: any[];
      encapsulation: string;
      events: any[];
      methods: any[];
      props: {
        attr: string;
        default: any;
        docs: string;
        docsTags: any[];
        mutable: boolean;
        name: string;
        optional: boolean;
        reflectToAttr: boolean;
        required: boolean;
        type: string;
      }[];
      readme: string;
      slots: any[];
      styles: any[];
      tag: string;
      usage: any;
    };
  }

  interface EnjinSidebar {
    'components': any;
  }
  interface EnjinSidebarAttributes extends StencilHTMLAttributes {
    'components'?: any;
  }

  interface EnjinStarRatingScoped {
    'disabled': boolean;
    'maxRating': number;
    'name': string;
    'setCurrentRating': (rating: any) => void;
    'value': string;
  }
  interface EnjinStarRatingScopedAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'maxRating'?: number;
    'name'?: string;
    'onFtStarRating'?: (event: CustomEvent) => void;
    'value'?: string;
  }

  interface EnjinStarRatingShadow {
    'disabled': boolean;
    'maxRating': number;
    'name': string;
    'setCurrentRating': (rating: any) => void;
    'value': string;
  }
  interface EnjinStarRatingShadowAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'maxRating'?: number;
    'name'?: string;
    'onFtStarRating'?: (event: CustomEvent) => void;
    'value'?: string;
  }

  interface EnjinStarRating {
    /**
    * Whether or not the field is disabled
    */
    'disabled': boolean;
    /**
    * The max available star rating
    */
    'maxRating': number;
    /**
    * The name of the input
    */
    'name': string;
    /**
    * Set the current rating
    */
    'setCurrentRating': (rating: any) => void;
    /**
    * The value of the rating input
    */
    'value': string;
  }
  interface EnjinStarRatingAttributes extends StencilHTMLAttributes {
    /**
    * Whether or not the field is disabled
    */
    'disabled'?: boolean;
    /**
    * The max available star rating
    */
    'maxRating'?: number;
    /**
    * The name of the input
    */
    'name'?: string;
    'onEnjinStarRating'?: (event: CustomEvent) => void;
    /**
    * The value of the rating input
    */
    'value'?: string;
  }

  interface EnjinTestComponent {}
  interface EnjinTestComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EnjinGallery': Components.EnjinGallery;
    'EnjinOrganism': Components.EnjinOrganism;
    'EnjinPayWithCard': Components.EnjinPayWithCard;
    'EnjinSidebarComponent': Components.EnjinSidebarComponent;
    'EnjinSidebar': Components.EnjinSidebar;
    'EnjinStarRatingScoped': Components.EnjinStarRatingScoped;
    'EnjinStarRatingShadow': Components.EnjinStarRatingShadow;
    'EnjinStarRating': Components.EnjinStarRating;
    'EnjinTestComponent': Components.EnjinTestComponent;
  }

  interface StencilIntrinsicElements {
    'enjin-gallery': Components.EnjinGalleryAttributes;
    'enjin-organism': Components.EnjinOrganismAttributes;
    'enjin-pay-with-card': Components.EnjinPayWithCardAttributes;
    'enjin-sidebar-component': Components.EnjinSidebarComponentAttributes;
    'enjin-sidebar': Components.EnjinSidebarAttributes;
    'enjin-star-rating-scoped': Components.EnjinStarRatingScopedAttributes;
    'enjin-star-rating-shadow': Components.EnjinStarRatingShadowAttributes;
    'enjin-star-rating': Components.EnjinStarRatingAttributes;
    'enjin-test-component': Components.EnjinTestComponentAttributes;
  }


  interface HTMLEnjinGalleryElement extends Components.EnjinGallery, HTMLStencilElement {}
  var HTMLEnjinGalleryElement: {
    prototype: HTMLEnjinGalleryElement;
    new (): HTMLEnjinGalleryElement;
  };

  interface HTMLEnjinOrganismElement extends Components.EnjinOrganism, HTMLStencilElement {}
  var HTMLEnjinOrganismElement: {
    prototype: HTMLEnjinOrganismElement;
    new (): HTMLEnjinOrganismElement;
  };

  interface HTMLEnjinPayWithCardElement extends Components.EnjinPayWithCard, HTMLStencilElement {}
  var HTMLEnjinPayWithCardElement: {
    prototype: HTMLEnjinPayWithCardElement;
    new (): HTMLEnjinPayWithCardElement;
  };

  interface HTMLEnjinSidebarComponentElement extends Components.EnjinSidebarComponent, HTMLStencilElement {}
  var HTMLEnjinSidebarComponentElement: {
    prototype: HTMLEnjinSidebarComponentElement;
    new (): HTMLEnjinSidebarComponentElement;
  };

  interface HTMLEnjinSidebarElement extends Components.EnjinSidebar, HTMLStencilElement {}
  var HTMLEnjinSidebarElement: {
    prototype: HTMLEnjinSidebarElement;
    new (): HTMLEnjinSidebarElement;
  };

  interface HTMLEnjinStarRatingScopedElement extends Components.EnjinStarRatingScoped, HTMLStencilElement {}
  var HTMLEnjinStarRatingScopedElement: {
    prototype: HTMLEnjinStarRatingScopedElement;
    new (): HTMLEnjinStarRatingScopedElement;
  };

  interface HTMLEnjinStarRatingShadowElement extends Components.EnjinStarRatingShadow, HTMLStencilElement {}
  var HTMLEnjinStarRatingShadowElement: {
    prototype: HTMLEnjinStarRatingShadowElement;
    new (): HTMLEnjinStarRatingShadowElement;
  };

  interface HTMLEnjinStarRatingElement extends Components.EnjinStarRating, HTMLStencilElement {}
  var HTMLEnjinStarRatingElement: {
    prototype: HTMLEnjinStarRatingElement;
    new (): HTMLEnjinStarRatingElement;
  };

  interface HTMLEnjinTestComponentElement extends Components.EnjinTestComponent, HTMLStencilElement {}
  var HTMLEnjinTestComponentElement: {
    prototype: HTMLEnjinTestComponentElement;
    new (): HTMLEnjinTestComponentElement;
  };

  interface HTMLElementTagNameMap {
    'enjin-gallery': HTMLEnjinGalleryElement
    'enjin-organism': HTMLEnjinOrganismElement
    'enjin-pay-with-card': HTMLEnjinPayWithCardElement
    'enjin-sidebar-component': HTMLEnjinSidebarComponentElement
    'enjin-sidebar': HTMLEnjinSidebarElement
    'enjin-star-rating-scoped': HTMLEnjinStarRatingScopedElement
    'enjin-star-rating-shadow': HTMLEnjinStarRatingShadowElement
    'enjin-star-rating': HTMLEnjinStarRatingElement
    'enjin-test-component': HTMLEnjinTestComponentElement
  }

  interface ElementTagNameMap {
    'enjin-gallery': HTMLEnjinGalleryElement;
    'enjin-organism': HTMLEnjinOrganismElement;
    'enjin-pay-with-card': HTMLEnjinPayWithCardElement;
    'enjin-sidebar-component': HTMLEnjinSidebarComponentElement;
    'enjin-sidebar': HTMLEnjinSidebarElement;
    'enjin-star-rating-scoped': HTMLEnjinStarRatingScopedElement;
    'enjin-star-rating-shadow': HTMLEnjinStarRatingShadowElement;
    'enjin-star-rating': HTMLEnjinStarRatingElement;
    'enjin-test-component': HTMLEnjinTestComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
